<?php

namespace App\DataProviders;

abstract class UserDataProvider
{
    public static function data(): array
    {
        return array(
            array('id' => '1','name' => 'Alice Johnson','email' => 'alice.johnson@example.com','phone' => '123-456-7890','email_verified_at' => '2023-12-22 14:40:43','password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'job_seeker','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/p1.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '3','name' => 'Charlie Brown','email' => 'charlie.brown@example.com','phone' => '345-678-9012','email_verified_at' => '2023-12-22 14:40:43','password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'job_seeker','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/p2.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '5','name' => 'John Davis','email' => 'emma.davis@example.com','phone' => '567-890-1234','email_verified_at' => '2023-12-22 14:40:43','password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'job_seeker','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/p3.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '7','name' => 'Grace Wilson','email' => 'grace.wilson@example.com','phone' => NULL,'email_verified_at' => NULL,'password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'job_seeker','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/p4.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '9','name' => 'Ivy Martinez','email' => 'ivy.martinez@example.com','phone' => '789-012-3456','email_verified_at' => '2023-12-22 14:40:43','password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'job_seeker','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/p5.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '11','name' => 'James Lee','email' => 'james.lee@example.com','phone' => '890-123-4567','email_verified_at' => '2023-12-22 14:40:43','password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'job_seeker','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/p6.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '13','name' => 'Katherine Turner','email' => 'katherine.turner@example.com','phone' => '901-234-5678','email_verified_at' => '2023-12-22 14:40:43','password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'job_seeker','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/p7.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '15','name' => 'Mia Taylor','email' => 'liam.taylor@example.com','phone' => '012-345-6789','email_verified_at' => '2023-12-22 14:40:43','password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'job_seeker','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/p8.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '17','name' => 'Alan Walker','email' => 'mia.walker@example.com','phone' => '234-567-8901','email_verified_at' => '2023-12-22 14:40:43','password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'job_seeker','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/p9.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '19','name' => 'Noah Harris','email' => 'noah.harris@example.com','phone' => '345-678-9012','email_verified_at' => '2023-12-22 14:40:43','password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'job_seeker','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/p10.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '31','name' => 'Elon Musk','email' => 'elon.musk@example.com','phone' => NULL,'email_verified_at' => NULL,'password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'employer','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/tesla-logo.png','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '33','name' => 'Tim Cook','email' => 'tim.cook@example.com','phone' => NULL,'email_verified_at' => NULL,'password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'employer','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/apple-logo.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '35','name' => 'Satya Nadella','email' => 'satya.nadella@example.com','phone' => NULL,'email_verified_at' => NULL,'password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'employer','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/microsoft-logo.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '37','name' => 'Sundar Pichai','email' => 'sundar.pichai@example.com','phone' => NULL,'email_verified_at' => NULL,'password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'employer','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/intel-logo.png','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '39','name' => 'Mark Zuckerberg','email' => 'mark.zuckerberg@example.com','phone' => NULL,'email_verified_at' => NULL,'password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'employer','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/cisco-logo.png','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '41','name' => 'Jeff Bezos','email' => 'jeff.bezos@example.com','phone' => NULL,'email_verified_at' => NULL,'password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'employer','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/amazon-logo.jpg','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '43','name' => 'Bill Gates','email' => 'bill.gates@example.com','phone' => NULL,'email_verified_at' => NULL,'password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'employer','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/google-logo.png','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '45','name' => 'Sheryl Sandberg','email' => 'sheryl.sandberg@example.com','phone' => NULL,'email_verified_at' => NULL,'password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'employer','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/facebook-logo.png','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '47','name' => 'Arvind Krishna','email' => 'arvind.krishna@example.com','phone' => NULL,'email_verified_at' => NULL,'password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'employer','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/ibm-logo.png','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43'),
            array('id' => '49','name' => 'Safra Catz','email' => 'safra.catz@example.com','phone' => NULL,'email_verified_at' => NULL,'password' => '$2y$12$OlQrKwGRg94TUNUeoiqeS.FcHEXAEoejw6NxIbUXL18quv.NKIr3K','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'two_factor_confirmed_at' => NULL,'role' => 'employer','remember_token' => NULL,'current_team_id' => NULL,'profile_photo_path' => 'profile-photos/oracle-logo.png','created_at' => '2023-12-22 14:40:43','updated_at' => '2023-12-22 14:40:43')
        );
    }
}
